### PR TITLE
chore: update host and user of the test DB

### PR DESCRIPTION
**Pull request by kellnerd**
Changed in the config files but not in the test DB script, see 814d07b3161908e82127b9ef53c04751dd20c77f.

### CODE REVIEW

**Review by MonkeyDo — APPROVED** [review]
Yes, I arrived at the same conclusion, but ran out of time to test. Thanks !

**Comment by kellnerd** [comment]
Only the CI is apparently not happy with the changed host...

**Comment by kellnerd** [comment]
I have zero experience with GitHub actions, but since your attempt also failed, I would try to change the host in line 63 instead?

**Comment by MonkeyDo** [comment]
> I have zero experience with GitHub actions, but since your attempt also failed, I would try to change the host in line 63 instead?
> 
> _Edit_: Yep, that did the trick.

Oh god. That's what I get for multi-tasking :p
Thanks for the assist!

**Pull request merged**
