### PR TITLE
Feat[BB-607] : display total number of entity present in a particular collection

### PR DESCRIPTION
**Pull request by endurance21**
### Problem
https://tickets.metabrainz.org/browse/BB-607

### Solution
Added indication for Total number of entities present in the given collection.

rec-tab

### Areas of Impact

src/client/components/pages/entities/author-table.js
src/client/components/pages/entities/edition-table.js
src/client/components/pages/entities/editionGroup-table.js
src/client/components/pages/entities/publisher-table.js
src/client/components/pages/entities/work-table.js

### CODE REVIEW

**Comment by endurance21** [comment]
@MonkeyDo  please review this pr

**Comment by MonkeyDo** [comment]
Hi @endurance21, there's already a pull request (#571)  in progress for this feature, so I'll close this one.
Do make sure that an issue isn't already reported or a PR open for it, to avoid spending time on an issue already solved :)

**Comment by endurance21** [comment]
@MonkeyDo  
PR #571  deals with showing no of entities in collection Page.
But this pr simply displays the size of the collection array using frontend logic on `Collection-table` .

We may reopen this pr if we intent to follow up these two are different ?

**Comment by MonkeyDo** [comment]
You are absolutely correct, sorry for the rushed decision!

**Review by MonkeyDo — CHANGES_REQUESTED** [review]
Thanks for opening this PR, and sorry again for closing it without looking at it well enough !

The way the total is displayed looks out of place. I'd rather see the information added to the existing header with all the rest of the collection's info.

Furthermore with the current PR, the total will be visible on pages other than the collection page (those edition-table, work-table, etc. components are reused in various pages), so adding the entity count to the CollectionAttributes component instead makes more sense.

**Comment by MonkeyDo** [comment]
Hi @endurance21 , I wanted to know if you wanted to try finishing this PR, or if I with your permission I should try it myself?

**Comment by endurance21** [comment]
Hey ! I wish I could take out some time of mine to finish this unfortunately I am busy with my semester exam right now.

If it can wait , I will try to catch up later or otherwise it would be my pleasure to allow you working on this.

**Comment by MonkeyDo** [comment]
Closed in favor of #742

**Pull request closed without merging**
