### PR TITLE
fix BB-718:CritiqueBrainz auth endpoint is called server-side

### PR DESCRIPTION
**Pull request by AVtheking**
Problem
https://tickets.metabrainz.org/browse/BB-718

Solution
I have applied a conditional check (typeof window!=="undefined") this check ensures that this function is called from the client side .

Areas of Impact

The changes were reflected in src/client/components/pages/entities/cbReviewModal.tsx

### CODE REVIEW

**Comment by AVtheking** [comment]
please review this

**Review by MonkeyDo — COMMENTED** [review]
Hello @AVtheking and thanks for submitting a PR !

Unfortunately, a similar PR was submitted prior to yours in #1041 and I will merge that one. Despite them not assigning the ticket to themselves they did open the PR first.

The solution is the same, so good work on that :)

However for future reference, you'll see that there are a lot of unrelated formatting changes committed as well which we don't want.
I assume your editor is set up to automatically format code with Prettier or some other formatter, but we use ESLint to do so (see [the eslint config at the root](https://github.com/metabrainz/bookbrainz-site/blob/master/.eslintrc.js))

**Comment by MonkeyDo** [comment]
Closing in favor of #1041

**Comment by MonkeyDo** [comment]
Actually @AVtheking I was just corrected and pointed out that you had reassigned the ticket to yourself even though it was already assigned to someone. Please don't do that it's bad form and creates confusion.

**Comment by AVtheking** [comment]
Ok sir

**Pull request closed without merging**
