### PR TITLE
BB-730: Rewrite test files using async/await syntax

### PR DESCRIPTION
**Pull request by faraz16iqbal**
Problem
[BB-673](https://tickets.metabrainz.org/browse/BB-673):
Across the codebase, we have asynchronous code written using promises, which is hard to read and to maintain and error-prone.

Solution
All this code was rewritten using the async/await syntax.

Areas of Impact
The changes were reflected in test/common.js

### CODE REVIEW

**Comment by MonkeyDo** [comment]
Sorry it took so long to answer @faraz16iqbal !
Yes, the modifications look great.
Should I merge the PR now or do you want to modify other files in the same PR?

**Comment by faraz16iqbal** [comment]
@MonkeyDo thank you for the review! I think I'll use this PR to convert all the files in one go.

**Comment by faraz16iqbal** [comment]
@MonkeyDo I mentioned there were some files that used the following syntax: 
`if (days === funRunnerDays) {
 editPromise = Promise.resolve(threshold);
			}`

Do these also need to be changed?

**Comment by MonkeyDo** [comment]
> 

Looking at that file with that code I don't think it's necessary to rewrite those as an async function.
ESLint will tell you an async function needs an await expression, and we don't have anything to await in that in this particular case.
I think you can leave those as-is.

**Comment by faraz16iqbal** [comment]
@MonkeyDo I have converted all tests files to follow the async-await syntax. Please review whenever you can!

**Review by MonkeyDo — APPROVED** [review]
And thank you for this one as well ! :)

**Pull request merged**
