### PR TITLE
BB-672: Rewrite entity folder using async/await

### PR DESCRIPTION
**Pull request by GandalfGwaihir**
### Problem

[BB-672](https://tickets.metabrainz.org/browse/BB-672):
Across the codebase we have asynchronous code written using promises, which is hard to read and to maintain and error-prone.

### Solution

All this code was rewritten using the async/await syntax.

### Areas of Impact

The changes were reflected in `src/server/routes/entity`

### CODE REVIEW

**Comment by RohanSasne** [comment]
Hey @MonkeyDo , fixed the merge conflict, i guess after the Wikipedia PR, there were some changes in that particular file so there was a conflict, anyway fixed it :)

**Review by MonkeyDo — CHANGES_REQUESTED** [review]
Generally looks pretty good, thanks for starting on this folder!

It looks like you can apply some of the same refactors to `edition.ts` in the same folder; any reason why you didn't?

**Comment by RohanSasne** [comment]
Hey @MonkeyDo, thanks for the review, I'm little busy for a few weeks, but I'll surely complete this PR and get it merged :)

**Comment by MonkeyDo** [comment]
Hi @RohanSasne !
Checking in to see if you would have some time to finish this PR, or if you would prefer to hand it off to me instead.

**Comment by Tarunmeena0901** [comment]
hey @MonkeyDo is this PR completed or may be i can complete this one for other files as well ?

**Comment by Tarunmeena0901** [comment]
yeah sure ...... just want to know if monkey has taken over this PR

**Comment by MonkeyDo** [comment]
Closing in favor of #1058

**Pull request closed without merging**
